// Build the CV PDF from the same data that drives the website.
//
//   data/*.json  ->  CV/cv/*.tex (generated)  ->  xelatex  ->  public/cv.pdf
//
// Run with:  npm run cv
//
// The .tex section files under CV/cv/ are OVERWRITTEN on every run — do not edit
// them by hand. To change the CV's *look*, edit CV/cv.tex or CV/academic-cv.cls.
// To change the CV's *content*, edit the JSON files under data/.

import { readFileSync, writeFileSync, copyFileSync, existsSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const DATA = (name) => resolve(ROOT, 'data', name);
const CV_DIR = resolve(ROOT, 'CV');
const SECTION = (name) => resolve(CV_DIR, 'cv', name);

const read = (p) => JSON.parse(readFileSync(p, 'utf8'));

const about = read(DATA('about.json'));
const education = read(DATA('education.json'));
const { publications } = read(DATA('publications.json'));
const teaching = read(DATA('teaching.json'));
const cv = read(DATA('cv.json'));

// --- LaTeX helpers ----------------------------------------------------------

/** Escape a plain string so it is safe to drop into LaTeX text. */
function tex(value) {
  return String(value ?? '')
    .replace(/\\/g, '\\textbackslash ')
    .replace(/([&%$#_])/g, '\\$1')
    .replace(/\{/g, '\\{')
    .replace(/\}/g, '\\}')
    .replace(/~/g, '\\textasciitilde ')
    .replace(/\^/g, '\\textasciicircum ');
}

const HEADER = '% AUTO-GENERATED by scripts/build-cv.mjs — do not edit by hand.\n';

const myName = about.name;

/** Bold the author entry that is me; escape everyone. */
function formatAuthors(authors = []) {
  return authors
    .map((a) =>
      a.toLowerCase().includes(myName.toLowerCase())
        ? `\\textbf{${tex(a)}}`
        : tex(a)
    )
    .join(', ');
}

/** One publication/talk -> a \cvpub citation body. */
function formatPublication(p) {
  const parts = [`${formatAuthors(p.authors)}.`, `\\emph{${tex(p.title)}}.`];
  if (p.venue) parts.push(`${tex(p.venue)}.`);
  if (p.year) parts.push(`${tex(p.year)}.`);
  if (p.note) parts.push(tex(p.note));
  if (p.highlight) parts.push(`\\textbf{${tex(p.highlight)}.}`);
  return parts.join(' ');
}

function formatTalk(t) {
  const parts = [];
  if (t.date) parts.push(`${tex(t.date)}.`);
  parts.push(`\\emph{${tex(t.title)}}.`);
  const where = [t.event, t.location].filter(Boolean).map(tex).join(', ');
  if (where) parts.push(`${where}.`);
  return parts.join(' ');
}

const cvpubs = (items, fmt) =>
  items.length
    ? `\\begin{cvpubs}\n\\small \\color{black}\n${items
        .map((it) => `\\cvpub{${fmt(it)}}`)
        .join('\n\n')}\n\\end{cvpubs}`
    : `\\begin{cvpubs}\n\\end{cvpubs}`;

/** A cvhonors table, or empty string when there are no rows. */
const cvhonors = (rows) =>
  rows.length
    ? `\\begin{cvhonors}\n${rows.join('\n')}\n\\end{cvhonors}`
    : '';

const writeSection = (file, body) => writeFileSync(SECTION(file), HEADER + body + '\n');

// --- Personal info (preamble + footer macros) -------------------------------

const now = new Date();
const cvDate = now.toLocaleDateString('en-US', { month: 'long', year: 'numeric' });
const position = tex(about.cvPosition).replace(/\s*·\s*/g, '{\\enskip\\cdotp\\enskip}');

const personal = [
  `\\name{${tex(about.name)}}{}`,
  `\\position{${position}}`,
  about.phone ? `\\mobile{${tex(about.phone)}}` : '',
  about.email ? `\\email{${tex(about.email)}}` : '',
  about.homepage ? `\\homepage{${tex(about.homepage.replace(/^https?:\/\//, ''))}}` : '',
  `\\newcommand{\\cvname}{${tex(about.name)}}`,
  `\\newcommand{\\cvdate}{${tex(cvDate)}}`,
]
  .filter(Boolean)
  .join('\n');
writeSection('_personal.tex', personal);

// --- Education --------------------------------------------------------------

const eduEntries = education.map((e) => {
  const bullets = [];
  if (e.advisor) bullets.push(`Advisor: Dr. ${tex(e.advisor)}`);
  for (const n of e.notes ?? []) bullets.push(tex(n));
  const desc = bullets.length
    ? `\n      \\begin{cvitems}\n${bullets
        .map((b) => `        \\item {${b}}`)
        .join('\n')}\n      \\end{cvitems}\n    `
    : '';
  return `  \\cventry\n    {${tex(e.degree)}}\n    {${tex(e.institution)}}\n    {${tex(e.location)}}\n    {${tex(e.date)}}\n    {${desc}}`;
});
writeSection(
  'education.tex',
  `\\cvsection{Education}\n\n\\begin{cventries}\n\n${eduEntries.join('\n\n')}\n\n\\end{cventries}`
);

// --- Professional Experience ------------------------------------------------

const expEntries = cv.experience.map((x) => {
  const bullets = (x.notes ?? []).map(tex);
  const desc = bullets.length
    ? `\n      \\begin{cvitems}\n${bullets
        .map((b) => `        \\item {${b}}`)
        .join('\n')}\n      \\end{cvitems}\n    `
    : '';
  return `  \\cventry\n    {${tex(x.role)}}\n    {${tex(x.title)}}\n    {${tex(x.organization)}}\n    {${tex(x.date)}}\n    {${desc}}`;
});
writeSection(
  'professional.tex',
  `\\cvsection{Professional Experience}\n\n${
    expEntries.length ? `\\begin{cventries}\n\n${expEntries.join('\n\n')}\n\n\\end{cventries}` : ''
  }`
);

// --- Publications (Published / In Review / In Prep) -------------------------

const pubsByStatus = (status) => publications.filter((p) => p.status === status);
const pubBlock = (heading, status) =>
  `\\cvsubsection{${heading}}\n\n${cvpubs(pubsByStatus(status), formatPublication)}`;
writeSection(
  'publications.tex',
  `\\cvsection{Publications}\n\n${[
    pubBlock('Published', 'published'),
    pubBlock('In Review', 'in_review'),
    pubBlock('In Prep', 'in_prep'),
  ].join('\n\n')}`
);

// --- Awards, Fellowships, & Grants ------------------------------------------

const awardRows = cv.awards.map(
  (a) => `  \\cvhonor\n    {${tex(a.title)}}\n    {${tex(a.organization)}}\n    {${tex(a.detail ?? '')}}\n    {${tex(a.date)}}`
);
writeSection(
  'honors.tex',
  `\\cvsection{Awards, Fellowships, \\& Grants}\n\n${cvhonors(awardRows)}`
);

// --- Presentations ----------------------------------------------------------

writeSection(
  'presentation.tex',
  `\\cvsection{Presentations}\n\n\\vspace{-0.3cm}\n\\begin{small}\\textit{* presenting author; \\textsuperscript{+} mentored undergraduate}\\end{small}\n\n\\cvsubsection{Invited Talks}\n\n${cvpubs(
    cv.presentations.invited,
    formatTalk
  )}\n\n\\cvsubsection{Contributed Presentations}\n\n${cvpubs(
    cv.presentations.contributed,
    formatTalk
  )}`
);

// --- Teaching ---------------------------------------------------------------

const roleLabel = { ta: 'Teaching Assistant', instructor: 'Instructor' };
const teachRows = teaching.map(
  (c) =>
    `  \\cvhonor\n    {${tex(c.course)}}\n    {${tex(roleLabel[c.role] ?? c.role)}}\n    {${tex(c.location ?? '')}}\n    {${tex(c.semester)}}`
);
writeSection(
  'teaching.tex',
  `\\cvsection{Teaching Experience}\n\n${cvhonors(teachRows)}`
);

// --- Mentoring --------------------------------------------------------------

const mentorRows = cv.mentoring.map(
  (m) => `  \\cvhonor\n    {${tex(m.name)}}\n    {${tex(m.relationship)}}\n    {${tex(m.location ?? '')}}\n    {${tex(m.date)}}`
);
writeSection('mentoring.tex', `\\cvsection{Mentoring}\n\n${cvhonors(mentorRows)}`);

// --- Outreach & Professional Development -------------------------------------

const serviceRows = cv.service.map(
  (s) => `  \\cvhonor\n    {${tex(s.organization)}}\n    {${tex(s.role)}}\n    {${tex(s.location ?? '')}}\n    {${tex(s.date)}}`
);
const developmentBody = cv.development.length
  ? `\\begin{cvpubs}\n${cv.development
      .map((d) => {
        const tail = [d.year, d.location].filter(Boolean).map(tex).join(', ');
        return `    \\cvpub{\\textbf{${tex(d.title)} }${tail ? `, ${tail}` : ''}}`;
      })
      .join('\n')}\n\\end{cvpubs}`
  : '';
const smallList = (lines) =>
  `\\begin{small} \\color{black}\n${lines.map((l) => `${tex(l)} \\\\`).join('\n')}\n\\end{small}`;

writeSection(
  'extracurricular.tex',
  [
    `\\cvsection{Outreach \\& Professional Development}`,
    ``,
    `\\cvsubsection{Service and Outreach}`,
    cvhonors(serviceRows),
    ``,
    `\\cvsubsection{Development}`,
    developmentBody,
    ``,
    `\\cvsubsection{Peer Review}`,
    smallList(cv.peerReview),
    ``,
    `\\cvsubsection{Professional Memberships}`,
    smallList(cv.memberships),
  ].join('\n')
);

console.log('✓ Generated CV/cv/*.tex from data/');

// --- Compile ----------------------------------------------------------------

// The template loads its bundled FontAwesome/Roboto fonts by name. Point
// XeTeX's font search at CV/fonts/ so they resolve without a system install.
const fontDir = resolve(CV_DIR, 'fonts');
const osFontDir = process.env.OSFONTDIR
  ? `${fontDir}${process.platform === 'win32' ? ';' : ':'}${process.env.OSFONTDIR}`
  : fontDir;

// Single command string (not args array) so this works with shell:true on both
// platforms without Node's DEP0190 warning. All arguments are static.
const latexmk = spawnSync(
  'latexmk -xelatex -interaction=nonstopmode -halt-on-error cv.tex',
  {
    cwd: CV_DIR,
    stdio: 'inherit',
    shell: true,
    env: { ...process.env, OSFONTDIR: osFontDir },
  }
);

if (latexmk.status !== 0) {
  console.error('\n✗ latexmk failed. See log above (CV/cv.log).');
  process.exit(latexmk.status ?? 1);
}

const built = resolve(CV_DIR, 'cv.pdf');
if (!existsSync(built)) {
  console.error('✗ Expected CV/cv.pdf was not produced.');
  process.exit(1);
}
copyFileSync(built, resolve(ROOT, 'public', 'cv.pdf'));
console.log('✓ Wrote public/cv.pdf');
